# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terragruntdemostorcon"
    key                  = "dev/terraform.tfstate"
    resource_group_name  = "terragruntdemo-rg"
    storage_account_name = "terragruntdemostoracc"
  }
}
